/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projectoad;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class PersonajesTableDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public PersonajesTableDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addTableRenderer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        generoComboBox = new javax.swing.JComboBox<>();
        posicionComboBox = new javax.swing.JComboBox<>();
        atributoComboBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        tablaJugadoresScrollPane = new javax.swing.JScrollPane();
        jugadoresTable = new javax.swing.JTable();
        informacionButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreLabel.setText("Nombre:");

        nombreTextField.setText("");

        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero..", "Hombre", "Mujer", "Desconocido", "Neutral" }));

        posicionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posicion..", "GK", "DF", "MF", "FW" }));

        atributoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atributo..", "Viento", "Bosque", "Fuego", "Montaña" }));

        buscarButton.setText("Buscar");

        jugadoresTable.setAutoCreateRowSorter(true);
        jugadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Icono", "Nombre", "Genero", "Posicion", "Atributo", "Pais"
            }
        ));
        tablaJugadoresScrollPane.setViewportView(jugadoresTable);

        informacionButton.setText("Mostrar..");

        jButton1.setText("Añadir..");

        jButton2.setText("Borrar..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaJugadoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atributoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(informacionButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atributoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaJugadoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informacionButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setBuscarButtonActionListener(ActionListener al){
        buscarButton.addActionListener(al);
    }
    
    public void setInformacionButtonActionListener(ActionListener al){
        informacionButton.addActionListener(al);
    }
    
    public String getJugadoresTableSelectedItem() {
        if(this.jugadoresTable.getSelectedRow() == -1){
            return null;
        }
        return this.jugadoresTable.getValueAt(this.jugadoresTable.getSelectedRow(), 0).toString();
    }
    
    public void addRowJugadoresTable(Vector row){
        DefaultTableModel dtm = (DefaultTableModel) this.jugadoresTable.getModel();
        dtm.addRow(row);
    }
    
    public void clearJugadoresTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.jugadoresTable.getModel();
        dtm.setRowCount(0);
        jugadoresTable.clearSelection();
        jugadoresTable.revalidate();
        jugadoresTable.repaint();
    }
    
    private void addTableRenderer() {
        jugadoresTable.getColumnModel().getColumn(0).setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel();
                label.setHorizontalAlignment(JLabel.CENTER);

                if (value instanceof ImageIcon) {
                    label.setIcon((ImageIcon) value);
                    label.setText("");
                } else {
                    label.setIcon(null);
                    label.setText(value != null ? value.toString() : "");
                }

                label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                
                if (hasFocus) {
                    label.setBorder(UIManager.getBorder("Table.focusCellHighlightBorder"));
                } else {
                    label.setBorder(null);
                }
                
                return label;
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> atributoComboBox;
    private javax.swing.JButton buscarButton;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JButton informacionButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jugadoresTable;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JComboBox<String> posicionComboBox;
    private javax.swing.JScrollPane tablaJugadoresScrollPane;
    // End of variables declaration//GEN-END:variables
}
