package inazuma.vistas.users;

import inazuma.controladores.userController.MusicController;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private static boolean musicaIniciada = false;
    
    public MainFrame() {
        initComponents();
        this.getContentPane().setBackground(new Color(255,255,255));
        loginButton.setBackground(new Color(255,112,40));
        registerButton.setBackground(new Color(255,112,40));
        guestButton.setBackground(new Color(255,112,40));
        menuBar.setVisible(false);
        if(!musicaIniciada) {
            MusicController musica = new MusicController();
            musica.play("src/resources/OpeningIE.wav");
            musicaIniciada = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        guestButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        sesionMenuItem = new javax.swing.JMenuItem();
        personajesTableMenuItem = new javax.swing.JMenuItem();
        equiposTableMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginButton.setText("Inicio Sesión");

        registerButton.setText("Registrar");

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoInazuma.png"))); // NOI18N
        imageLabel.setText("jLabel2");

        guestButton.setText("Invitado");
        guestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestButtonActionPerformed(evt);
            }
        });

        menuMenu.setText("File");

        sesionMenuItem.setText("Sesión..");
        menuMenu.add(sesionMenuItem);

        personajesTableMenuItem.setText("Tabla de Personajes..");
        menuMenu.add(personajesTableMenuItem);

        equiposTableMenuItem.setText("Tabla de Equipos..");
        menuMenu.add(equiposTableMenuItem);

        salirMenuItem.setText("Salir");
        menuMenu.add(salirMenuItem);

        menuBar.add(menuMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestButtonActionPerformed

    }//GEN-LAST:event_guestButtonActionPerformed

    public void setPersonajesTableMenuItemActionListener(ActionListener al){
        personajesTableMenuItem.addActionListener(al);
    }

    public void setSesionMenuItemActionListener(ActionListener al){
        sesionMenuItem.addActionListener(al);
    }
    
    public void setEquiposTableMenuItemActionListener(ActionListener al){
        equiposTableMenuItem.addActionListener(al);
    }
    
    public void setSalirMenuItemActionListener(ActionListener al){
        salirMenuItem.addActionListener(al);
    }
    
    public void addLoginButtonActionListener(ActionListener al) {
        this.loginButton.addActionListener(al);
    }
    
    public void addRegisterButtonActionListener(ActionListener al) {
        this.registerButton.addActionListener(al);
    }
    
    public void updateForLogin() {
        loginButton.setVisible(false);
        registerButton.setVisible(false);
        guestButton.setVisible(false);
        menuBar.setVisible(true);
    }
    
    public void enableDisableBotonesLogin(boolean enableDisable){
        loginButton.setVisible(enableDisable);
        registerButton.setVisible(enableDisable);
        guestButton.setVisible(enableDisable);
        menuBar.setVisible(true);
    }
    
    public void invitadoActionListener(ActionListener al){
        this.guestButton.addActionListener(al);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem equiposTableMenuItem;
    public javax.swing.JButton guestButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem personajesTableMenuItem;
    private javax.swing.JButton registerButton;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JMenuItem sesionMenuItem;
    // End of variables declaration//GEN-END:variables
}
