package inazuma.vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMenuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        sesionMenuItem = new javax.swing.JMenuItem();
        personajesTableMenuItem = new javax.swing.JMenuItem();
        equiposTableMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMenu.setText("File");

        sesionMenuItem.setText("Sesión..");
        menuMenu.add(sesionMenuItem);

        personajesTableMenuItem.setText("Tabla de Personajes..");
        menuMenu.add(personajesTableMenuItem);

        equiposTableMenuItem.setText("Tabla de Equipos..");
        menuMenu.add(equiposTableMenuItem);

        salirMenuItem.setText("Salir");
        menuMenu.add(salirMenuItem);

        menuMenuBar.add(menuMenu);

        setJMenuBar(menuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPersonajesTableMenuItemActionListener(ActionListener al){
        personajesTableMenuItem.addActionListener(al);
    }

    public void setSesionMenuItemActionListener(ActionListener al){
        sesionMenuItem.addActionListener(al);
    }
    
    public void setEquiposTableMenuItemActionListener(ActionListener al){
        equiposTableMenuItem.addActionListener(al);
    }
    
    public void setSalirMenuItemActionListener(ActionListener al){
        salirMenuItem.addActionListener(al);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem equiposTableMenuItem;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuBar menuMenuBar;
    private javax.swing.JMenuItem personajesTableMenuItem;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JMenuItem sesionMenuItem;
    // End of variables declaration//GEN-END:variables
}
