package inazuma.vistas;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author dam2_alu09@inf.ald
 */
public class PersonajesTableDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public PersonajesTableDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addTableRenderer();
        this.setTitle("Tabla de Personajes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        generoComboBox = new javax.swing.JComboBox<>();
        posicionComboBox = new javax.swing.JComboBox<>();
        atributoComboBox = new javax.swing.JComboBox<>();
        aplicarButton = new javax.swing.JButton();
        tablaJugadoresScrollPane = new javax.swing.JScrollPane();
        jugadoresTable = new javax.swing.JTable();
        mostrarButton = new javax.swing.JButton();
        anhadirButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreLabel.setText("Nombre:");

        nombreTextField.setText("");

        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero..", "Hombre", "Mujer", "Desconocido", "Neutral" }));

        posicionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posicion..", "GK", "DF", "MF", "FW" }));

        atributoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atributo..", "Viento", "Bosque", "Fuego", "Montaña" }));

        aplicarButton.setText("Aplicar");

        jugadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Icono", "Nombre", "Genero", "Posicion", "Atributo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jugadoresTable.setRowHeight(80);
        tablaJugadoresScrollPane.setViewportView(jugadoresTable);

        mostrarButton.setText("Mostrar..");

        anhadirButton.setText("Añadir..");

        borrarButton.setText("Borrar");

        modificarButton.setText("Modificar..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaJugadoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atributoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aplicarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(borrarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anhadirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atributoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aplicarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaJugadoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarButton)
                    .addComponent(anhadirButton)
                    .addComponent(borrarButton)
                    .addComponent(modificarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setModificarButtonActionListener( ActionListener al){
        modificarButton.addActionListener(al);
    }
    
    public void setAnhadirButtonActionListener(ActionListener al){
        anhadirButton.addActionListener(al);
    }
    
    public void setBorrarButtonActionListener(ActionListener al){
        borrarButton.addActionListener(al);
    }
    
    public void setAplicarButtonActionListener(ActionListener al){
        aplicarButton.addActionListener(al);
    }
    
    public void setMostrarButtonActionListener(ActionListener al){
        mostrarButton.addActionListener(al);
    }

    public String getAtributoComboBoxSelectedValue() {
        if(atributoComboBox.getSelectedIndex()!=0){
            return atributoComboBox.getSelectedItem().toString();
        }
        return "";
    }

    public String getGeneroComboBoxSelectedValue() {
        if(generoComboBox.getSelectedIndex()!=0){
            return generoComboBox.getSelectedItem().toString();
        }
        return "";
    }

    public String getNombreTextFieldValue() {
        if(nombreTextField.getText()!=null){
            return nombreTextField.getText();
        }
        return "";
    }

    public String getPosicionComboBoxSelectedValue() {
        if(posicionComboBox.getSelectedIndex()!=0){
            return posicionComboBox.getSelectedItem().toString();
        }
        return "";
    }
    
    public int getJugadoresTableSelectedItem() {
        return jugadoresTable.getSelectedRow();
    }
    
    public void addRowJugadoresTable(Vector row){
        DefaultTableModel dtm = (DefaultTableModel) this.jugadoresTable.getModel();
        dtm.addRow(row);
    }
    
    public void clearJugadoresTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.jugadoresTable.getModel();
        dtm.setRowCount(0);
        jugadoresTable.clearSelection();
        jugadoresTable.revalidate();
        jugadoresTable.repaint();
    }
    
    public void desactivarSeleccion() {
        jugadoresTable.clearSelection();
    }
    
    private void addTableRenderer() {
        jugadoresTable.getColumnModel().getColumn(0).setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel();
                label.setHorizontalAlignment(JLabel.CENTER);
                if (value instanceof ImageIcon) {
                    label.setIcon((ImageIcon) value);
                    label.setText("");
                } else {
                    label.setIcon(null);
                    label.setText(value != null ? value.toString() : "");
                }
                label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                if (hasFocus) {
                    label.setBorder(UIManager.getBorder("Table.focusCellHighlightBorder"));
                } else {
                    label.setBorder(null);
                }
                return label;
            }
        });
        jugadoresTable.getColumnModel().getColumn(4).setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel();
                label.setHorizontalAlignment(JLabel.CENTER);
                if (value instanceof ImageIcon) {
                    label.setIcon((ImageIcon) value);
                    label.setText("");
                } else {
                    label.setIcon(null);
                    label.setText(value != null ? value.toString() : "");
                }
                label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                if (hasFocus) {
                    label.setBorder(UIManager.getBorder("Table.focusCellHighlightBorder"));
                } else {
                    label.setBorder(null);
                }
                return label;
            }
        });
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jugadoresTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jugadoresTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jugadoresTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirButton;
    private javax.swing.JButton aplicarButton;
    private javax.swing.JComboBox<String> atributoComboBox;
    private javax.swing.JButton borrarButton;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JTable jugadoresTable;
    private javax.swing.JButton modificarButton;
    private javax.swing.JButton mostrarButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JComboBox<String> posicionComboBox;
    private javax.swing.JScrollPane tablaJugadoresScrollPane;
    // End of variables declaration//GEN-END:variables
}
